[workspace]
members = ["generator"]

[package]
name = "tags"
version = "0.1.0"
edition = "2021"
authors = ["ğŸ‡«ğŸ‡· Romain TRUCHI <romain.truchi.06@gmail.com>"]

[dependencies]

[profile.dev]
debug = false
strip = true

[profile.dev.package."*"]
debug = false
strip = true
opt-level = 3
debug-assertions = false
overflow-checks = false
codegen-units = 16
